#!/usr/bin/env bash
#
# Bootstraps the whole Karaka stack on a single Linux VM.
#
# Written after Render's free tier proved unusable for Keycloak: 512 MB and 0.1 CPU
# failed from both directions — the kernel killed the process at Keycloak's default
# heap settings, and capping metaspace produced OutOfMemoryError: Metaspace. Keycloak
# wants around 200 MB of metaspace before any heap, and the same logs showed a TCP bind
# blocking for two seconds, so the CPU was inadequate independently of the memory.
#
# Target: Oracle Cloud Always Free ARM (Ampere A1) — up to 4 cores and 24 GB, free
# indefinitely. Any VM with >=2 GB works. Runs Keycloak, the service AND Postgres
# locally, so no managed database is needed.
#
# Usage, as a sudo-capable user on a fresh Ubuntu 22.04/24.04 VM:
#   curl -fsSL <raw-url>/scripts/vm-bootstrap.sh | bash -s -- <PUBLIC_HOST>
# where PUBLIC_HOST is the VM's public IP or DNS name, e.g. 129.153.x.x
set -euo pipefail

PUBLIC_HOST="${1:-}"
REPO="${KARAKA_REPO:-https://github.com/HarshSingh21/karaka-ui.git}"
BRANCH="${KARAKA_BRANCH:-main}"
DIR="${KARAKA_DIR:-$HOME/karaka-ui}"

if [[ -z "$PUBLIC_HOST" ]]; then
  echo "usage: vm-bootstrap.sh <public-ip-or-hostname>" >&2
  exit 1
fi

echo "══ 1. Docker"
if ! command -v docker >/dev/null; then
  sudo apt-get update -qq
  sudo apt-get install -y -qq ca-certificates curl git
  sudo install -m 0755 -d /etc/apt/keyrings
  sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  sudo chmod a+r /etc/apt/keyrings/docker.asc
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    | sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
  sudo apt-get update -qq
  sudo apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
  sudo usermod -aG docker "$USER"
  echo "   installed (a re-login is needed for the docker group; sudo is used below)"
fi

echo "══ 2. Source"
if [[ -d "$DIR/.git" ]]; then
  git -C "$DIR" fetch -q origin && git -C "$DIR" checkout -q "$BRANCH" && git -C "$DIR" pull -q
else
  git clone -q --branch "$BRANCH" "$REPO" "$DIR"
fi
cd "$DIR"

echo "══ 3. Secrets"
# Generated on the VM and never leaving it. | & + / = are stripped because the realm
# substitution uses sed with | as its delimiter and & is its backreference character.
gen() { openssl rand -base64 "${1:-32}" | tr -d '\n|&+/='; }

# Stripping +/= leaves only alphanumerics, which cannot satisfy the realm's
# specialChars(1) rule. Passwords Keycloak validates must use genpw().
genpw() { printf '%s#Aa9' "$(gen "${1:-18}")"; }
if [[ ! -f .env ]]; then
  WEB=$(gen 32)
  cat > .env <<EOF
# Generated by vm-bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Not in git.
POSTGRES_PASSWORD=$(gen 32)
KC_ADMIN_USER=admin
KC_ADMIN_PASSWORD=$(gen 24)
KEYCLOAK_CLIENT_SECRET=$WEB
KARAKA_WEB_SECRET=$WEB
KARAKA_API_SECRET=$(gen 32)
DEMO_USER_PASSWORD=$(genpw 18)
APP_BASE_URL=http://$PUBLIC_HOST:8080
EOF
  chmod 600 .env
  echo "   .env written (mode 600)"
else
  echo "   .env already present — left alone"
fi

echo "══ 4. Realm"
./scripts/render-realm.sh

echo "══ 5. Start Keycloak and Postgres"
sudo docker compose up -d
printf "   waiting for Keycloak "
for _ in $(seq 1 90); do
  if curl -fsS -m 5 -o /dev/null "http://localhost:8081/realms/karaka/.well-known/openid-configuration"; then
    echo " ready"; break
  fi
  printf "."; sleep 4
done

echo "══ 6. Build and start the service"
sudo docker build -q -f service/Dockerfile -t karaka-service:local . >/dev/null
sudo docker rm -f karaka-service >/dev/null 2>&1 || true
# shellcheck disable=SC1091
set -a; source .env; set +a
sudo docker run -d --name karaka-service --restart unless-stopped \
  --network host \
  -e KEYCLOAK_ISSUER_URI="http://$PUBLIC_HOST:8081/realms/karaka" \
  -e KEYCLOAK_CLIENT_SECRET="$KEYCLOAK_CLIENT_SECRET" \
  karaka-service:local >/dev/null

printf "   waiting for the service "
for _ in $(seq 1 60); do
  if curl -fsS -m 5 -o /dev/null http://localhost:8080/actuator/health; then echo " ready"; break; fi
  printf "."; sleep 3
done

cat <<EOF

══ Done

  App        http://$PUBLIC_HOST:8080
  Keycloak   http://$PUBLIC_HOST:8081/admin

  Sign in as ankit / $(grep DEMO_USER_PASSWORD .env | cut -d= -f2)
  Keycloak admin: admin / $(grep KC_ADMIN_PASSWORD .env | cut -d= -f2)

  Open ports 8080 and 8081 in BOTH places or nothing is reachable:
    - the cloud provider's security list / VCN ingress rules
    - the VM firewall:
        sudo iptables -I INPUT -p tcp --dport 8080 -j ACCEPT
        sudo iptables -I INPUT -p tcp --dport 8081 -j ACCEPT
        sudo netfilter-persistent save
  Oracle Cloud images ship with a default-DROP iptables policy, so the security list
  alone is not enough — this catches almost everyone once.

  This is plain HTTP. Before anything real, put a reverse proxy with TLS in front
  (Caddy gets a certificate automatically) and set KARAKA_COOKIE_SECURE=true.
EOF
